a = imread('1.jpg')
b = imread('2.jpg')
c = imread('3.jpg')
d = imread('4.jpg')
e = imread('5.jpg')
f = imread('6.jpg')

subplot(2,3,1)
imshow(a)
title('first 1 best feature')
subplot(2,3,2)
imshow(b)
title('first 2 best feature')
subplot(2,3,3)
imshow(c)
title('first 3 best feature')
subplot(2,3,4)
imshow(d)
title('first 4 best feature')
subplot(2,3,5)
imshow(e)
title('first 5 best feature')
subplot(2,3,6)
imshow(f)
title('first 6 best feature')